#!/bin/bash

#Extract subdomain from domain
subdomain=$(echo $1 | cut -d '.' -f 1-2)
domain="`echo $1 | awk -F . '{print $2}'`"

echo "subdomain = $subdomain and domain = $domain"

#Check if domain already exists
if [ -d "/var/www/$subdomain" ]; then
        echo "Error: Domain already exists. Aborting..."
        exit
fi
#Check if domain is valid
if [[ $1 != $subdomain.tom-ausloos.sb.uclllabs.be ]]; then
        echo "Error: Invalid Domain. Aborting..."
        exit
else

#Create documentroot for subdomain with welcome message in index page
 	mkdir /var/www/$subdomain
 	touch /var/www/$subdomain/index.html
 	echo 'welcome '$subdomain > /var/www/$subdomain/index.html

#Create vhost
 	touch /etc/apache2/sites-available/$subdomain.$domain.conf
 	echo "<VirtualHost *:80>
         	ServerName $1
         	DocumentRoot /var/www/$subdomain
         	LogLevel info
         	ErrorLog "${APACHE_LOG_DIR}"/$subdomain.$domain-error.log
         	CustomLog "${APACHE_LOG_DIR}"/$subdomain.$domain-access.log combined
 	</VirtualHost>" > /etc/apache2/sites-available/$subdomain.$domain.conf

 	a2ensite $subdomain.$domain

# Add record to zonefile
	sudo dns_add_record -t A $subdomain 193.191.177.199 tom-ausloos.sb.uclllabs.be

# Reload changed services
	systemctl restart bind9
	systemctl restart apache2

echo "Created V-host and documentroot and added record to zone"
fi
